prompt Importing table t_trabajos...
set feedback off
set define off
insert into t_trabajos (ID_TRABAJO, TIPO, ACCION, FECHA_INICIO, TIEMPO_INICIO, INTERVALO_REPETICION, FECHA_FIN, COMENTARIOS, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION, PROGRAMA)
values (2000, 'STORED_PROCEDURE', 'K_MONITOREO.P_PROCESAR_MONITOREOS', null, null, 'FREQ=MONTHLY;BYMONTHDAY=1;BYHOUR=0;BYMINUTE=10;BYSECOND=0;', null, 'Trabajo de monitoreo de conflictos - Mensual', null, null, 'P_MONITOREO_CONFLICTOS');

insert into t_trabajos (ID_TRABAJO, TIPO, ACCION, FECHA_INICIO, TIEMPO_INICIO, INTERVALO_REPETICION, FECHA_FIN, COMENTARIOS, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION, PROGRAMA)
values (2001, 'STORED_PROCEDURE', 'K_MONITOREO.P_PROCESAR_MONITOREOS', null, null, 'FREQ=WEEKLY;BYMONTHDAY=2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31;BYDAY=MON;BYHOUR=0;BYMINUTE=10;BYSECOND=0;', null, 'Trabajo de monitoreo de conflictos - Semanal', null, null, 'P_MONITOREO_CONFLICTOS');

insert into t_trabajos (ID_TRABAJO, TIPO, ACCION, FECHA_INICIO, TIEMPO_INICIO, INTERVALO_REPETICION, FECHA_FIN, COMENTARIOS, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION, PROGRAMA)
values (2002, 'STORED_PROCEDURE', 'K_MONITOREO.P_PROCESAR_MONITOREOS', null, null, 'FREQ=DAILY;BYMONTHDAY=2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31;BYDAY=TUE,WED,THU,FRI,SAT,SUN;BYHOUR=0;BYMINUTE=10;BYSECOND=0;', null, 'Trabajo de monitoreo de conflictos - Diaria', null, null, 'P_MONITOREO_CONFLICTOS');

insert into t_trabajos (ID_TRABAJO, TIPO, ACCION, FECHA_INICIO, TIEMPO_INICIO, INTERVALO_REPETICION, FECHA_FIN, COMENTARIOS, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION, PROGRAMA)
values (2003, 'STORED_PROCEDURE', 'K_MONITOREO.P_PROCESAR_MONITOREOS', null, null, 'FREQ=HOURLY;BYHOUR=12;BYMINUTE=10;BYSECOND=0;', null, 'Trabajo de monitoreo de conflictos - Cada 12 Horas', null, null, 'P_MONITOREO_CONFLICTOS');

insert into t_trabajos (ID_TRABAJO, TIPO, ACCION, FECHA_INICIO, TIEMPO_INICIO, INTERVALO_REPETICION, FECHA_FIN, COMENTARIOS, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION, PROGRAMA)
values (2004, 'STORED_PROCEDURE', 'K_MONITOREO.P_PROCESAR_MONITOREOS', null, null, 'FREQ=HOURLY;BYHOUR=6,18;BYMINUTE=10;BYSECOND=0;', null, 'Trabajo de monitoreo de conflictos - Cada 6 Horas', null, null, 'P_MONITOREO_CONFLICTOS');

insert into t_trabajos (ID_TRABAJO, TIPO, ACCION, FECHA_INICIO, TIEMPO_INICIO, INTERVALO_REPETICION, FECHA_FIN, COMENTARIOS, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION, PROGRAMA)
values (2005, 'STORED_PROCEDURE', 'K_MONITOREO.P_PROCESAR_MONITOREOS', null, null, 'FREQ=HOURLY;BYHOUR=2,4,8,10,14,16,20,22;BYMINUTE=10;BYSECOND=0;', null, 'Trabajo de monitoreo de conflictos - Cada 2 Horas', null, null, 'P_MONITOREO_CONFLICTOS');

insert into t_trabajos (ID_TRABAJO, TIPO, ACCION, FECHA_INICIO, TIEMPO_INICIO, INTERVALO_REPETICION, FECHA_FIN, COMENTARIOS, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION, PROGRAMA)
values (2006, 'STORED_PROCEDURE', 'K_MONITOREO.P_PROCESAR_MONITOREOS', null, null, 'FREQ=HOURLY;BYHOUR=1,3,5,7,9,11,13,15,17,19,21,23;BYMINUTE=10;BYSECOND=0;', null, 'Trabajo de monitoreo de conflictos - Cada Hora', null, null, 'P_MONITOREO_CONFLICTOS');

prompt Done.
