prompt Importing table T_OPERACION_PARAMETROS...
set feedback off
set define off
insert into T_OPERACION_PARAMETROS (ID_OPERACION, NOMBRE, VERSION, ORDEN, ACTIVO, TIPO_DATO, FORMATO, LONGITUD_MAXIMA, OBLIGATORIO, VALOR_DEFECTO, ETIQUETA, DETALLE, VALORES_POSIBLES)
values (70, 'USUARIO', '0.1.0', 1, 'S', 'S', null, null, 'S', null, null, null, null);

insert into T_OPERACION_PARAMETROS (ID_OPERACION, NOMBRE, VERSION, ORDEN, ACTIVO, TIPO_DATO, FORMATO, LONGITUD_MAXIMA, OBLIGATORIO, VALOR_DEFECTO, ETIQUETA, DETALLE, VALORES_POSIBLES)
values (70, 'CAMPO', '0.1.0', 2, 'S', 'S', null, null, 'S', null, null, null, null);

insert into T_OPERACION_PARAMETROS (ID_OPERACION, NOMBRE, VERSION, ORDEN, ACTIVO, TIPO_DATO, FORMATO, LONGITUD_MAXIMA, OBLIGATORIO, VALOR_DEFECTO, ETIQUETA, DETALLE, VALORES_POSIBLES)
values (70, 'DATO', '0.1.0', 3, 'S', 'S', null, null, 'S', null, null, null, null);

prompt Done.
