prompt Importing table t_grupos...
set feedback off
set define off

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'General', 'GLO', null, null, 1, 'A', 'A', null, 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Cerristas', 'GLO', null, null, 1, 'A', 'A', 'CER', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Olimpistas', 'GLO', null, null, 1, 'A', 'A', 'OLI', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Liberteños', 'GLO', null, null, 1, 'A', 'A', 'LIB', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Solenses', 'GLO', null, null, 1, 'A', 'A', 'SOL', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Luqueños', 'GLO', null, null, 1, 'A', 'A', 'LUQ', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Santanianos', 'GLO', null, null, 1, 'A', 'A', 'SAN', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Nacionalófilos', 'GLO', null, null, 1, 'A', 'A', 'NAC', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Aurinegros', 'GLO', null, null, 1, 'A', 'A', 'GUA', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Rayaditos', 'GLO', null, null, 1, 'A', 'A', 'SSL', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Kelitos', 'GLO', null, null, 1, 'A', 'A', 'RIV', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Águilas de Luque', 'GLO', null, null, 1, 'A', 'A', 'GEN', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Itagüeños', 'GLO', null, null, 1, 'A', 'A', '12O', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ID_JORNADA_INICIO, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (null, 'PRI-APE20', 'Guaireños', 'GLO', null, null, 1, 'A', 'A', 'GUI', 'N');

prompt Done.
