prompt Importing table t_planteles...
set feedback off
set define off

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-DEMO', 'CER', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-DEMO', 'GUA', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-DEMO', 'LIB', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-DEMO', 'LUQ', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-DEMO', 'NAC', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-DEMO', 'OLI', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'CER', 39, 19, 12, 3, 4, 33, 18, 15, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'CAP', 24, 19, 6, 6, 7, 17, 19, -2, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'GEN', 31, 18, 8, 7, 3, 25, 14, 11, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'GUA', 34, 19, 11, 1, 7, 32, 22, 10, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'IND', 17, 19, 5, 2, 12, 15, 33, -18, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'LIB', 25, 19, 7, 4, 8, 26, 24, 2, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'LUQ', 27, 19, 7, 6, 6, 28, 25, 3, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'NAC', 17, 18, 3, 8, 7, 16, 29, -13, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'OLI', 33, 19, 9, 6, 4, 29, 16, 13, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'RUB', 20, 19, 5, 5, 9, 15, 25, -10, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'SOL', 24, 19, 6, 6, 7, 20, 26, -6, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA17', 'TRI', 18, 19, 4, 6, 9, 17, 22, -5, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'CER', 16, 6, 5, 1, 0, 14, 4, 10, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'CAP', 4, 6, 1, 1, 4, 6, 11, -5, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'GEN', 7, 6, 2, 1, 3, 13, 16, -3, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'GUA', 5, 6, 1, 2, 3, 5, 10, -5, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'IND', 7, 6, 2, 1, 3, 8, 7, 1, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'LIB', 11, 6, 3, 2, 1, 11, 8, 3, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'LUQ', 7, 6, 2, 1, 3, 6, 9, -3, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'NAC', 11, 6, 3, 2, 1, 6, 3, 3, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'OLI', 13, 6, 4, 1, 1, 12, 5, 7, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'SAN', 10, 6, 2, 4, 0, 8, 3, 5, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', 'SOL', 4, 6, 1, 1, 4, 8, 17, -9, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE18', '3DF', 4, 6, 1, 1, 4, 7, 11, -4, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'CER', 80, 44, 22, 14, 8, 72, 42, 30, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'CAP', 48, 44, 12, 12, 20, 50, 72, -22, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'GEN', 43, 43, 10, 13, 20, 59, 77, -18, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'GUA', 50, 44, 12, 14, 18, 54, 60, -6, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'IND', 40, 44, 8, 16, 20, 44, 64, -20, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'LIB', 74, 44, 20, 14, 10, 66, 40, 26, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'LUQ', 50, 44, 12, 14, 18, 46, 60, -14, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'NAC', 54, 44, 12, 18, 14, 56, 62, -6, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'OLI', 98, 44, 30, 8, 6, 96, 40, 56, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'SAN', 56, 44, 14, 14, 16, 44, 58, -14, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', 'SOL', 66, 44, 18, 12, 14, 58, 60, -2, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-CLA18', '3DF', 49, 43, 12, 13, 18, 63, 73, -10, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'CER', 43, 22, 13, 4, 5, 48, 25, 23, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'CAP', 26, 22, 6, 8, 8, 24, 32, -8, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'SAN', 13, 22, 2, 7, 13, 15, 39, -24, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'GEN', 16, 22, 3, 7, 12, 21, 42, -21, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'GUA', 37, 22, 10, 7, 5, 37, 29, 8, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'LIB', 37, 22, 11, 4, 7, 39, 29, 10, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'NAC', 23, 22, 5, 8, 9, 19, 27, -8, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'OLI', 54, 22, 16, 6, 0, 61, 17, 44, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'RIV', 28, 22, 7, 7, 8, 25, 31, -6, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'SSL', 27, 22, 8, 3, 11, 33, 37, -4, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'SOL', 26, 22, 8, 2, 12, 31, 43, -12, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE19', 'LUQ', 31, 22, 8, 7, 7, 28, 30, -2, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', '12O', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'CER', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'GEN', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'GUA', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'LIB', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'LUQ', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'NAC', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'OLI', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'RIV', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'GUI', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'SOL', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('PRI-APE20', 'SSL', null, null, null, null, null, null, null, null, null, null);

prompt Done.
