prompt Importing table t_grupos...
set feedback off
set define off

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (1, 'PRI-APE20', 'General', 'GLO', null, null, 'A', 'A', null, 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (2, 'PRI-APE20', 'Cerristas', 'GLO', null, null, 'A', 'A', 'CER', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (3, 'PRI-APE20', 'Olimpistas', 'GLO', null, null, 'A', 'A', 'OLI', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (4, 'PRI-APE20', 'Liberteños', 'GLO', null, null, 'A', 'A', 'LIB', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (5, 'PRI-APE20', 'Solenses', 'GLO', null, null, 'A', 'A', 'SOL', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (6, 'PRI-APE20', 'Luqueños', 'GLO', null, null, 'A', 'A', 'LUQ', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (7, 'PRI-APE20', 'Santanianos', 'GLO', null, null, 'A', 'A', 'SAN', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (8, 'PRI-APE20', 'Nacionalófilos', 'GLO', null, null, 'A', 'A', 'NAC', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (9, 'PRI-APE20', 'Aurinegros', 'GLO', null, null, 'A', 'A', 'GUA', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (10, 'PRI-APE20', 'Rayaditos', 'GLO', null, null, 'A', 'A', 'SSL', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (11, 'PRI-APE20', 'Kelitos', 'GLO', null, null, 'A', 'A', 'RIV', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (12, 'PRI-APE20', 'Águilas de Luque', 'GLO', null, null, 'A', 'A', 'GEN', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (13, 'PRI-APE20', 'Itagüeños', 'GLO', null, null, 'A', 'A', '12O', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (14, 'PRI-APE20', 'Guaireños', 'GLO', null, null, 'A', 'A', 'GUI', 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (15, 'PRI-DEMO', 'Grupo General 1', 'GLO', null, null, 'A', 'A', null, 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (16, 'PRI-DEMO', 'Grupo Privado 1', 'PRI', 1, null, 'A', 'A', null, 'N');

insert into t_grupos (ID_GRUPO, ID_TORNEO, DESCRIPCION, TIPO, ID_USUARIO_ADMINISTRADOR, FECHA_CREACION, ESTADO, SITUACION, ID_CLUB, TODOS_INVITAN)
values (17, 'PRI-DEMO', 'Grupo Privado 2', 'PRI', 2, null, 'A', 'A', null, 'N');

prompt Done.
