prompt Importing table t_estadios...
set feedback off
set define off

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (1, 'GENERAL PABLO ROJAS', 'OLLA AZULGRANA, LA NUEVA OLLA', null, 'A', 177, null, null, 43, 'CER');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (2, 'LICENCIADO ERICO GALEANO SEGOVIA', null, null, 'A', 177, null, null, 124, 'CAP');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (3, 'GENERAL ADRIÁN JARA', null, null, 'A', 177, null, null, 120, 'GEN');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (4, 'ROGELIO SILVINO LIVIERES', 'DOS BOCAS, LA TOLDERÍA', null, 'A', 177, null, null, 43, 'GUA');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (5, 'RICARDO GREGOR', null, null, 'A', 177, null, null, 43, 'IND');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (6, 'DOCTOR NICOLÁS LEOZ', 'TUYUCUA', null, 'A', 177, null, null, 43, 'LIB');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (7, 'FELICIANO CÁCERES', null, null, 'A', 177, null, null, 120, 'LUQ');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (8, 'ARSENIO ERICO', 'VISERA', null, 'A', 177, null, null, 43, 'NAC');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (9, 'MANUEL FERREIRA', 'PARA UNO', null, 'A', 177, null, null, 43, 'OLI');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (10, 'ARBOLEDA', 'ARBOLEDA', null, 'A', 177, null, null, 43, 'RUB');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (11, 'LUIS ALFONSO GIAGNI', null, null, 'A', 177, null, null, 116, 'SOL');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (12, 'MARTÍN TORRES', null, null, 'A', 177, null, null, 43, 'TRI');

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (13, 'DEFENSORES DEL CHACO', null, null, 'A', 177, null, null, 43, null);

insert into t_estadios (ID_ESTADIO, NOMBRE_OFICIAL, OTROS_NOMBRES, CAPACIDAD, ESTADO, ID_PAIS, ID_CIUDAD, DIRECCION, ALTURA, ID_CLUB)
values (14, 'UNIÓN AGRÍCOLA', null, null, 'A', 177, null, null, null, 'SAN');

prompt Done.
