prompt Importing table t_clubes...
set feedback off
set define off

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('CER', null, 'CLUB CERRO PORTEÑO', 'CICLON, CLUB DEL PUEBLO, LA MITAD MAS UNO', to_date('01-10-1912', 'dd-mm-yyyy'), 'https://cerro.com.py', '@CCP1912oficial', null, 'PRI', 'CERRO PORTEÑO', 77);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('CAP', null, 'CLUB DEPORTIVO CAPIATA', 'ESCOBERO, DEPOR, CAPIATEÑO, AURIAZUL, EQUIPO MITOLOGICO', to_date('04-09-2008', 'dd-mm-yyyy'), null, '@DCapiataOficial', null, 'INT', 'DEPORTIVO CAPIATÁ', 2121);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('GEN', null, 'GENERAL DIAZ FBC', 'AGUILAS DE LUQUE, PAJAROS BLANCOS', to_date('22-09-1917', 'dd-mm-yyyy'), null, '@ClubGralDiaz', null, 'PRI', 'GENERAL DÍAZ', 1027);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('GUA', null, 'CLUB GUARANI', 'AURINEGRO, INDIO, LEGENDARIO, ABORIGEN, RAZA', to_date('12-10-1903', 'dd-mm-yyyy'), null, '@ClubGuarani', null, 'PRI', 'GUARANÍ', 115);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('IND', null, 'INDEPENDIENTE FBC DE CAMPO GRANDE', 'INDE, CAMPOGRANDENSE', to_date('20-09-1925', 'dd-mm-yyyy'), null, '@IndeFBC', null, 'INT', 'INDEPENDIENTE FBC', null);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('LIB', null, 'CLUB LIBERTAD', 'GUMARELO, GUMA, REPOLLERO', to_date('30-07-1905', 'dd-mm-yyyy'), 'http://www.clublibertad.com.py', '@Libertad_Guma', null, 'PRI', 'LIBERTAD', 69);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('LUQ', null, 'CLUB SPORTIVO LUQUEÑO', 'CHANCHON, KURE LUQUE, AURIAZUL, AZUL Y ORO', to_date('01-05-1921', 'dd-mm-yyyy'), null, '@SpLuquenOficial', null, 'PRI', 'SPORTIVO LUQUEÑO', 213);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('NAC', null, 'CLUB NACIONAL', 'ACADEMIA, NACIONAL QUERIDO, ALBO, TRICO', to_date('05-06-1904', 'dd-mm-yyyy'), null, '@clubnacionalpy', null, 'PRI', 'NACIONAL (P)', 214);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('OLI', null, 'CLUB OLIMPIA', 'DECANO, REY DE COPAS, EXPRESO DECANO, FRANJEADO', to_date('25-07-1902', 'dd-mm-yyyy'), 'https://clubolimpia.com.py', '@elClubOlimpia', null, 'PRI', 'OLIMPIA', 215);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('RUB', null, 'CLUB RUBIO ÑU', 'RUBIO, ALBIVERDE, ÑUENSE', to_date('24-08-1913', 'dd-mm-yyyy'), null, '@rubionu1913', null, 'INT', 'RUBIO ÑU', null);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('SOL', null, 'CLUB SOL DE AMERICA', 'DANZARIN', to_date('22-03-1909', 'dd-mm-yyyy'), null, '@SoldeAmericapy', null, 'PRI', 'SOL DE AMÉRICA', 604);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('TRI', null, 'CLUB SPORTIVO TRINIDENSE', 'TRIQUI', to_date('11-08-1935', 'dd-mm-yyyy'), null, '@CST_1935', null, 'INT', 'SPORTIVO TRINIDENSE', null);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('SSL', null, 'CLUB SPORTIVO SAN LORENZO', 'RAYADITO', to_date('17-04-1930', 'dd-mm-yyyy'), null, '@SanLorenzo1930', null, 'PRI', 'SAN LORENZO', 2119);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('SAN', null, 'CLUB DEPORTIVO SANTANÍ', 'SANTA, ALBINEGRA, DEPOR', to_date('27-02-2009', 'dd-mm-yyyy'), null, '@clubsantani', null, 'INT', 'DEPORTIVO SANTANÍ', 2120);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('3DF', null, 'CLUB ATLÉTICO 3 DE FEBRERO', 'EL GIGANTE DEL INTERIOR, EL ROJO PARANAENSE, EL TIGRE DEL ESTE', to_date('20-11-1970', 'dd-mm-yyyy'), null, '@CA3F', null, 'INT', 'ATLÉTICO 3 DE FEBRERO', null);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('12O', null, 'CLUB 12 DE OCTUBRE DE ITAUGUÁ', 'EL 12, LOS TEJEDORES, HIJOS DE COLÓN', to_date('14-08-1914', 'dd-mm-yyyy'), null, '@12deOctubreI', null, 'PRI', '12 DE OCTUBRE', 210);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('GUI', null, 'GUAIREÑA FÚTBOL CLUB', 'GUA''I', to_date('28-03-2016', 'dd-mm-yyyy'), null, '@GuairenaClub', null, 'PRI', 'GUAIREÑA', 6746);

insert into t_clubes (ID_CLUB, ID_PERSONA, NOMBRE_OFICIAL, OTROS_NOMBRES, FUNDACION, PAGINA_WEB, TWITTER, FACEBOOK, ID_DIVISION, NOMBRE_CORTO, ID_IMPORTACION)
values ('RIV', null, 'RIVER PLATE', 'EL KELITO', null, null, null, null, 'PRI', 'RIVER PLATE', 3220);

prompt Done.
