prompt Importing table t_torneos...
set feedback off
set define off

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-DEMO', null, null, 'TORNEO MOCKUP FANTASY', null, null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-APE17', 'PRI', 2017, 'TORNEO APERTURA 2017', 'DON MARIO A. SAPRIZA', null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-CLA17', 'PRI', 2017, 'TORNEO CLAUSURA 2017', 'DR. HASSEL AGUILAR SOSA', null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-APE18', 'PRI', 2018, 'TORNEO APERTURA 2018', 'CENTENARIO DEL ESTADIO DEFENSORES DEL CHACO', null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-CLA18', 'PRI', 2018, 'TORNEO CLAUSURA 2018', 'DR. GERÓNIMO ANGULO GASTÓN', null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-APE19', 'PRI', 2019, 'TORNEO APERTURA 2019', 'VÍCTOR GENES', null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-CLA19', 'PRI', 2019, 'TORNEO CLAUSURA 2019', 'DON RANULFO MIRANDA', null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-APE20', 'PRI', 2020, 'TORNEO APERTURA 2020', 'DR. EMILIO INSFRÁN VILLALBA', null, 'N');

insert into t_torneos (ID_TORNEO, ID_DIVISION, TEMPORADA, TITULO, DENOMINACION_OFICIAL, SALDO_INICIAL, ACTUAL)
values ('PRI-CLA20', 'PRI', 2020, 'TORNEO CLAUSURA 2020', 'PROF. CRISTÓBAL MALDONADO', null, 'S');

prompt Done.
