prompt Importing table t_planteles...
set feedback off
set define off
insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'ARG', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'BOL', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'BRA', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'CHI', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'COL', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'ECU', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'PAR', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'PER', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'URU', null, null, null, null, null, null, null, null, null, null);

insert into t_planteles (ID_TORNEO, ID_CLUB, PUNTOS, PARTIDOS_JUGADOS, PARTIDOS_GANADOS, PARTIDOS_EMPATADOS, PARTIDOS_PERDIDOS, GOLES_FAVOR, GOLES_CONTRA, DIFERENCIA_GOLES, PENALES_FAVOR, PENALES_CONTRA)
values ('ELS-QAT22', 'VEN', null, null, null, null, null, null, null, null, null, null);

prompt Done.
