prompt
prompt Instalando operaciones...
prompt -----------------------------------
prompt
@@scripts/operations/monitoreo/aut/sesiones_expiradas.sql
@@scripts/operations/monitoreo/fan/alta_baja_torneo.sql
@@scripts/operations/monitoreo/fan/clubes_nulos_torneos.sql
@@scripts/operations/monitoreo/fan/escudos_pendientes_clubes.sql
@@scripts/operations/monitoreo/fan/puntajes_pendientes_partidos.sql
@@scripts/operations/monitoreo/fan/servicio_datos_error_desconocido.sql
@@scripts/operations/monitoreo/fan/servicio_datos_version_driver.sql
@@scripts/operations/parametros/_/contexto.sql
@@scripts/operations/parametros/_/parametros_automaticos.sql
@@scripts/operations/reporte/gen/listar_significados.sql
@@scripts/operations/reporte/gen/version_sistema.sql
@@scripts/operations/servicio/aut/bloquear_usuario.sql
@@scripts/operations/servicio/aut/cambiar_clave.sql
@@scripts/operations/servicio/aut/cambiar_estado_sesion.sql
@@scripts/operations/servicio/aut/cambiar_estado_usuario.sql
@@scripts/operations/servicio/aut/datos_dispositivo.sql
@@scripts/operations/servicio/aut/datos_usuario.sql
@@scripts/operations/servicio/aut/desbloquear_usuario.sql
@@scripts/operations/servicio/aut/editar_dato_usuario.sql
@@scripts/operations/servicio/aut/editar_usuario.sql
@@scripts/operations/servicio/aut/generar_otp.sql
@@scripts/operations/servicio/aut/iniciar_sesion.sql
@@scripts/operations/servicio/aut/recuperar_clave.sql
@@scripts/operations/servicio/aut/recuperar_dato_usuario.sql
@@scripts/operations/servicio/aut/refrescar_sesion.sql
@@scripts/operations/servicio/aut/registrar_clave.sql
@@scripts/operations/servicio/aut/registrar_dispositivo.sql
@@scripts/operations/servicio/aut/registrar_ubicacion.sql
@@scripts/operations/servicio/aut/registrar_usuario.sql
@@scripts/operations/servicio/aut/tiempo_expiracion_token.sql
@@scripts/operations/servicio/aut/validar_clave_aplicacion.sql
@@scripts/operations/servicio/aut/validar_credenciales.sql
@@scripts/operations/servicio/aut/validar_otp.sql
@@scripts/operations/servicio/aut/validar_sesion.sql
@@scripts/operations/servicio/fan/abandonar_grupo.sql
@@scripts/operations/servicio/fan/calificar.sql
@@scripts/operations/servicio/fan/datos_grupo.sql
@@scripts/operations/servicio/fan/editar_grupo.sql
@@scripts/operations/servicio/fan/enviar_mensaje_amigo.sql
@@scripts/operations/servicio/fan/enviar_mensaje_grupo.sql
@@scripts/operations/servicio/fan/invitar_usuario.sql
@@scripts/operations/servicio/fan/listar_amigos.sql
@@scripts/operations/servicio/fan/listar_clubes.sql
@@scripts/operations/servicio/fan/listar_comentarios.sql
@@scripts/operations/servicio/fan/listar_divisiones.sql
@@scripts/operations/servicio/fan/listar_fases.sql
@@scripts/operations/servicio/fan/listar_grupos.sql
@@scripts/operations/servicio/fan/listar_jornadas.sql
@@scripts/operations/servicio/fan/listar_mensajes_amigo.sql
@@scripts/operations/servicio/fan/listar_mensajes_grupo.sql
@@scripts/operations/servicio/fan/listar_partidos.sql
@@scripts/operations/servicio/fan/listar_predicciones_partidos.sql
@@scripts/operations/servicio/fan/listar_reacciones.sql
@@scripts/operations/servicio/fan/listar_torneos.sql
@@scripts/operations/servicio/fan/reaccionar.sql
@@scripts/operations/servicio/fan/realizar_comentario.sql
@@scripts/operations/servicio/fan/realizar_prediccion.sql
@@scripts/operations/servicio/fan/registrar_grupo.sql
@@scripts/operations/servicio/fan/responder_ingreso_grupo.sql
@@scripts/operations/servicio/fan/responder_invitacion.sql
@@scripts/operations/servicio/fan/responder_solicitud_amistad.sql
@@scripts/operations/servicio/fan/seguir_division.sql
@@scripts/operations/servicio/fan/solicitar_amistad.sql
@@scripts/operations/servicio/fan/solicitar_ingreso_grupo.sql
@@scripts/operations/servicio/fan/suscribir.sql
@@scripts/operations/servicio/gen/guardar_archivo.sql
@@scripts/operations/servicio/gen/listar_aplicaciones.sql
@@scripts/operations/servicio/gen/listar_barrios.sql
@@scripts/operations/servicio/gen/listar_ciudades.sql
@@scripts/operations/servicio/gen/listar_departamentos.sql
@@scripts/operations/servicio/gen/listar_errores.sql
@@scripts/operations/servicio/gen/listar_paises.sql
@@scripts/operations/servicio/gen/listar_significados.sql
@@scripts/operations/servicio/gen/recuperar_archivo.sql
@@scripts/operations/servicio/gen/recuperar_texto.sql
@@scripts/operations/servicio/gen/significado_codigo.sql
@@scripts/operations/servicio/gen/valor_parametro.sql
@@scripts/operations/servicio/gen/version_servicio.sql
@@scripts/operations/servicio/gen/version_sistema.sql
@@scripts/operations/trabajo/fan/actualizacion_partidos.sql
@@scripts/operations/trabajo/fan/cierre_predicciones_{id_partido}.sql
@@scripts/operations/trabajo/fan/fin_partido_{id_partido}.sql
@@scripts/operations/trabajo/fan/partido_en_juego_{id_partido}.sql
@@scripts/operations/trabajo/fan/pre_cierre_predicciones_{id_partido}.sql
@@scripts/operations/trabajo/gen/monitoreo_conflictos_diario.sql
@@scripts/operations/trabajo/gen/monitoreo_conflictos_hora.sql
@@scripts/operations/trabajo/gen/monitoreo_conflictos_mensual.sql
@@scripts/operations/trabajo/gen/monitoreo_conflictos_semanal.sql
@@scripts/operations/trabajo/gen/monitoreo_conflictos_12_horas.sql
@@scripts/operations/trabajo/gen/monitoreo_conflictos_2_horas.sql
@@scripts/operations/trabajo/gen/monitoreo_conflictos_6_horas.sql
